# 2023 날씨데이터 머신러닝

In [19]:
import pandas as pd
weather=pd.read_excel("weather2023.xlsx",index_col='date')
weather.head()

            location loc_name  temp  rain  wind  humi  sunshine  cloud
date
2023-01-01       108       서울  -0.2   NaN   2.7  55.0       9.0    1.3
2023-01-02       108       서울  -4.5   NaN   2.5  46.0       9.1    0.0
2023-01-03       108       서울  -5.0   NaN   1.8  49.0       9.1    0.0
2023-01-04       108       서울  -1.8   NaN   1.9  51.0       8.7    1.9
2023-01-05       108       서울  -1.6   NaN   1.6  58.1       4.7    3.6

In [20]:
weather.isnull().sum()
weather.drop(['location','loc_name','rain'], axis=1, inplace=True)
weather.isnull().sum()

temp        0
wind        0
humi        0
sunshine    0
cloud       0
dtype: int64

In [ ]:
weather.head()

            temp  wind  humi  sunshine  cloud
date
2023-01-01  -0.2   2.7  55.0       9.0    1.3
2023-01-02  -4.5   2.5  46.0       9.1    0.0
2023-01-03  -5.0   1.8  49.0       9.1    0.0
2023-01-04  -1.8   1.9  51.0       8.7    1.9
2023-01-05  -1.6   1.6  58.1       4.7    3.6