## 데이터 전처리 개념 p.55

In [8]:
f=open("name.txt", encoding="utf-8")
data=f.read()
print(data)
f.close()

# r 읽기(기본값, 생략) : 파일이 반드시 존재해야함. 파일이 없으면 오류
# w 쓰기 : 파일이 이미 존재하면 기존 내용을 지우고 새로 작성, 파일이 없으면 새 파일 생성
# a 추가 : 파일이 존재하면 기존 내용의 끝에 추가, 파일이 없으면 새로 생성

In [9]:
f=open("name.txt", 'w')
while True:
    team=input("팀: ")
    if not team:
        break
    f.write(team + "\n")
f.close()
#write() : 데이터를 파일에 문자로 기록, 자동 줄바꿈이 되지 않음

## 64쪽 문법 실습

In [10]:
import pandas as pd

data = {
    '이름' : ['유비', '관우', '장비'],
    '1차지필' : [92, 89, 71],
    '2차지필' : [88, 90, 84],
    '수행1'  : [93, 85, 67],
    '수행2'  : [95, 78, 70],
    '등급'   : ['A', 'B', 'C']
}
df = pd.DataFrame(data)
df
df.to_excel("my_grade.xlsx", index=False)

In [11]:

df=pd.read_excel("my_grade.xlsx")
df.head()

# pd.read_excel() : 엑셀 파일을 읽어 DataFrame객체로 반환
# head() 또는 tail() : DataFrame의 상위 또는 하위 5개 행을 반환

add_df=pd.DataFrame([{
    '이름' : '조자룡',
    '1차지필' : 63,
    '2차지필' : 75,
    '수행1' : 84,
    '수행2' : 79,
    '등급' : 'C'
}])
modi_file=pd.concat([df, add_df], ignore_index=True)
modi_file.to_excel("new_grade.xlsx", index=False)
modi_file

# concat() : 두 개의 데이터 프레임을 합침
# to_excel() : DataFrame객체를 엑셀 파일로 저장
# index=False : 인덱스는 저장하지 않음

    이름  1차지필  2차지필  수행1  수행2 등급
0   유비    92    88   93   95  A
1   관우    89    90   85   78  B
2   장비    71    84   67   70  C
3  조자룡    63    75   84   79  C

In [12]:
import pandas as pd
df=pd.read_excel("club.xlsx")
df
add_df=pd.DataFrame([{
    '학번': 10512,
    '이름': '김하늘',
    '학년': 1,
    '동아리': 'AI연구부',
    '역할': '부원'
}])
new_df=pd.concat([df, add_df], ignore_index=True)
# index=True : 인덱스를 새로 생성, index=False : 기존 인덱스를 유지
new_df.to_excel("new_club.xlsx", index=False)
new_df

FileNotFoundError: [Errno 2] No such file or directory: 'club.xlsx'

## 데이터 전처리(2) 학습지 시작

In [21]:
import pandas as pd
df=pd.read_excel("data_preprocess.xlsx")
df

       name    age   address            job
0   Jackson   27.0   Gangwon          Sales
1     Lucas   15.0     Seoul   Student(mid)
2       Mia    NaN    Sejong       Cashiers
3   Abigail   24.0     Busan        Waiters
4     James   28.0      Jeju        Analyst
5  Benjamin   34.0  Gyeonggi       Cashiers
6   William  180.0     Ulsan  Student(high)
7   Abigail   24.0     Busan        Waiters
8     Emily   31.0       NaN         Driver
9     Henry   43.0     Daegu         Doctor

In [22]:
df_modi=df.drop(7) #중복값 삭제
# df_modi=df.drop_duplicates() #중복된행 자동제거
df_modi.dropna(inplace=True) #결측값 삭제
df_modi.loc[6,'age']=18 #이상치 정리
print(df_modi.iloc[6,3])
df_modi

Doctor

       name   age   address            job
0   Jackson  27.0   Gangwon          Sales
1     Lucas  15.0     Seoul   Student(mid)
3   Abigail  24.0     Busan        Waiters
4     James  28.0      Jeju        Analyst
5  Benjamin  34.0  Gyeonggi       Cashiers
6   William  18.0     Ulsan  Student(high)
9     Henry  43.0     Daegu         Doctor

In [23]:
#데이터프레임에서 하나의 열을 선택하면 '시리즈' 형태가 된다.

df['name']

#시리즈(series) : 다양한 자료형을 저장할 수 있는 1차원 배열
#데이터프레임은 이러한 시리즈가 2개이상 모인 것, 둘 이상의 열을 선택하면 데이터프레임 형태가 유지

0     Jackson
1       Lucas
2         Mia
3     Abigail
4       James
5    Benjamin
6     William
7     Abigail
8       Emily
9       Henry
Name: name, dtype: str

In [24]:
df[['name', 'age']]

       name    age
0   Jackson   27.0
1     Lucas   15.0
2       Mia    NaN
3   Abigail   24.0
4     James   28.0
5  Benjamin   34.0
6   William  180.0
7   Abigail   24.0
8     Emily   31.0
9     Henry   43.0

In [25]:
df_col1=df_modi['name']
print(df_col1)
print(type(df_modi))
df_col2=df_modi[['age','job']]
print(df_col2)
print(type(df_col2))

# 행 선택 : loc[] iloc[]
# - 개별 특성을 갖는 데이터집합
# - 행의 선택은 '행 이름',또는 '인덱스번호'로 선택
# print(df_modi.loc[3]) --> 인덱스 3번 행
# print(df_modi.iloc[3]) --> 세 번째 행

0     Jackson
1       Lucas
3     Abigail
4       James
5    Benjamin
6     William
9       Henry
Name: name, dtype: str
<class 'pandas.DataFrame'>
    age            job
0  27.0          Sales
1  15.0   Student(mid)
3  24.0        Waiters
4  28.0        Analyst
5  34.0       Cashiers
6  18.0  Student(high)
9  43.0         Doctor
<class 'pandas.DataFrame'>

In [26]:
print(df_modi.loc[3])
print(df_modi.iloc[3])

name       Abigail
age           24.0
address      Busan
job        Waiters
Name: 3, dtype: object
name         James
age           28.0
address       Jeju
job        Analyst
Name: 4, dtype: object

In [ ]:
df_modi['age']=df_modi['age'].astype('int')
df_modi.sort_values(by='name', ascending=False, inplace=True) 
#sort_values() : 데이터프레임을 특정 열을 기준으로 정렬
#inplace=True : 정렬된 결과를 원본 데이터프레임에 반영, inplace=False : 정렬된 결과를 새로운 데이터프레임으로 반환
df_modi

       name  age   address            job
6   William   18     Ulsan  Student(high)
1     Lucas   15     Seoul   Student(mid)
4     James   28      Jeju        Analyst
0   Jackson   27   Gangwon          Sales
9     Henry   43     Daegu         Doctor
5  Benjamin   34  Gyeonggi       Cashiers
3   Abigail   24     Busan        Waiters

- is null(): 데이터프레임의 열 항목에서 결측값이 있는 경우 True반환
- fillna(): 데이터프레임에서 결측값을 원하는 값으로 변경하는 메서드
- value counts(): 빈도수 집계