## 데이터 전처리 개념 p.55

In [12]:
f=open("name.txt", encoding="utf-8")
data=f.read()
print(data)
f.close()

토트넘
PSG
바이에른 뮌헨
울버햄튼

In [15]:
f=open("name.txt", 'w')
while True:
    team=input("팀: ")
    if not team:
        break
    f.write(team + "\n")
f.close()

## 64쪽 문법 실습

In [24]:
%pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

data = {
    '이름' : ['유비', '관우', '장비'],
    '1차지필' : [92, 89, 71],
    '2차지필' : [88, 90, 84],
    '수행1'  : [93, 85, 67],
    '수행2'  : [95, 78, 70],
    '등급'   : ['A', 'B', 'C']
}
df = pd.DataFrame(data)
df
df.to_excel("my_grade.xlsx", index=False)

In [4]:

df=pd.read_excel("my_grade.xlsx")
df

add_df=pd.DataFrame([{
    '이름' : '조자룡',
    '1차지필' : 63,
    '2차지필' : 75,
    '수행1' : 84,
    '수행2' : 79,
    '등급' : 'C'
}])
modi_file=pd.concat([df, add_df], ignore_index=True)
modi_file.to_excel("new_grade.xlsx", index=False)
modi_file

    이름  1차지필  2차지필  수행1  수행2 등급
0   유비    92    88   93   95  A
1   관우    89    90   85   78  B
2   장비    71    84   67   70  C
3  조자룡    63    75   84   79  C

In [7]:
import pandas as pd
df=pd.read_excel("club.xlsx")
df
add_df=pd.DataFrame([{
    '학번': 10512,
    '이름': '김하늘',
    '학년': 1,
    '동아리': 'AI연구부',
    '역할': '부원'
}])
new_df=pd.concat([df, add_df], ignore_index=True)
new_df.to_excel("new_club.xlsx", index=False)
new_df

      학번   이름  학년     동아리  역할
0  10401  이민호   1  AI 연구부  부장
1  10405  박서연   1  AI 연구부  부원
2  10503  최지우   1  AI 연구부  부원
3  10512  김하늘   1   AI연구부  부원

## 데이터 전처리(2) 학습지 시작

In [8]:
import pandas as pd
df=pd.read_excel("data_preprocess.xlsx")
df

       name    age   address            job
0   Jackson   27.0   Gangwon          Sales
1     Lucas   15.0     Seoul   Student(mid)
2       Mia    NaN    Sejong       Cashiers
3   Abigail   24.0     Busan        Waiters
4     James   28.0      Jeju        Analyst
5  Benjamin   34.0  Gyeonggi       Cashiers
6   William  180.0     Ulsan  Student(high)
7   Abigail   24.0     Busan        Waiters
8     Emily   31.0       NaN         Driver
9     Henry   43.0     Daegu         Doctor

In [14]:
df_modi=df.drop(7)
df_modi.dropna(inplace=True)
df_modi.loc[6,'age']=18
print(df_modi.iloc[6,3])
df_modi

Doctor

       name   age   address            job
0   Jackson  27.0   Gangwon          Sales
1     Lucas  15.0     Seoul   Student(mid)
3   Abigail  24.0     Busan        Waiters
4     James  28.0      Jeju        Analyst
5  Benjamin  34.0  Gyeonggi       Cashiers
6   William  18.0     Ulsan  Student(high)
9     Henry  43.0     Daegu         Doctor

In [15]:
df['name']

0     Jackson
1       Lucas
2         Mia
3     Abigail
4       James
5    Benjamin
6     William
7     Abigail
8       Emily
9       Henry
Name: name, dtype: str

In [ ]:
df[['name', 'age']]

       name    age
0   Jackson   27.0
1     Lucas   15.0
2       Mia    NaN
3   Abigail   24.0
4     James   28.0
5  Benjamin   34.0
6   William  180.0
7   Abigail   24.0
8     Emily   31.0
9     Henry   43.0

In [24]:
df_col1=df_modi['name']
print(df_col1)
print(type(df_modi))
df_col2=df_modi[['age','job']]
print(df_col2)
print(type(df_col2))

0     Jackson
1       Lucas
3     Abigail
4       James
5    Benjamin
6     William
9       Henry
Name: name, dtype: str
<class 'pandas.DataFrame'>
    age            job
0  27.0          Sales
1  15.0   Student(mid)
3  24.0        Waiters
4  28.0        Analyst
5  34.0       Cashiers
6  18.0  Student(high)
9  43.0         Doctor
<class 'pandas.DataFrame'>

In [26]:
print(df_modi.loc[3])
print(df_modi.iloc[3])

name       Abigail
age           24.0
address      Busan
job        Waiters
Name: 3, dtype: object
name         James
age           28.0
address       Jeju
job        Analyst
Name: 4, dtype: object

In [29]:
df_modi['age']=df_modi['age'].astype('int')
df_modi.sort_values(by='name', ascending=False, inplace=True)
df_modi

       name  age   address            job
6   William   18     Ulsan  Student(high)
1     Lucas   15     Seoul   Student(mid)
4     James   28      Jeju        Analyst
0   Jackson   27   Gangwon          Sales
9     Henry   43     Daegu         Doctor
5  Benjamin   34  Gyeonggi       Cashiers
3   Abigail   24     Busan        Waiters